LangString addOrReinstall ${LANG_CATALAN} "Afegeix o reinstal·la components"
LangString alreadyInstalled ${LANG_CATALAN} "Ja està instal·lat"
LangString alreadyInstalledLong ${LANG_CATALAN} "${PRODUCTNAME} ${VERSION} ja està instal·lat. Seleccioneu l'operació que vulgueu fer i premeu Següent per continuar."
LangString appRunning ${LANG_CATALAN} "{{product_name}} està obert! Tanqueu-lo i torneu-ho a provar."
LangString appRunningOkKill ${LANG_CATALAN} "{{product_name}} està obert!$\nPremeu D'acord per tancar-lo."
LangString chooseMaintenanceOption ${LANG_CATALAN} "Trieu l'operació de manteniment que vulgueu fer."
LangString choowHowToInstall ${LANG_CATALAN} "Trieu com voleu instal·lar ${PRODUCTNAME}."
LangString createDesktop ${LANG_CATALAN} "Crea una drecera a l'escriptori"
LangString dontUninstall ${LANG_CATALAN} "No desinstal·lis"
LangString dontUninstallDowngrade ${LANG_CATALAN} "No desinstal·lis (instal·lar una versió anterior sense desinstal·lar està desactivat en aquest instal·lador)"
LangString failedToKillApp ${LANG_CATALAN} "No s'ha pogut tancar {{product_name}}. Tanqueu-lo i torneu-ho a provar."
LangString installingWebview2 ${LANG_CATALAN} "S'està instal·lant WebView2..."
LangString newerVersionInstalled ${LANG_CATALAN} "Ja hi ha instal·lada una versió més recent de ${PRODUCTNAME}. No es recomana instal·lar una versió anterior. Si realment voleu instal·lar aquesta versió anterior, és recomanable desinstal·lar primer la versió actual. Seleccioneu l'operació que vulgueu fer i premeu Següent per continuar."
LangString older ${LANG_CATALAN} "anterior"
LangString olderOrUnknownVersionInstalled ${LANG_CATALAN} "Hi ha una versió $R4 de ${PRODUCTNAME} instal·lada al sistema. És recomanable desinstal·lar la versió actual abans de continuar. Seleccioneu l'operació que vulgueu fer i premeu Següent per continuar."
LangString silentDowngrades ${LANG_CATALAN} "Instal·lar una versió anterior està desactivat en aquest instal·lador. No es pot continuar amb l'instal·lador silenciós; feu servir l'instal·lador d'interfície gràfica.$\n"
LangString unableToUninstall ${LANG_CATALAN} "No s'ha pogut desinstal·lar."
LangString uninstallApp ${LANG_CATALAN} "Desinstal·la ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_CATALAN} "Desinstal·la abans d'instal·lar"
LangString unknown ${LANG_CATALAN} "desconeguda"
LangString webview2AbortError ${LANG_CATALAN} "No s'ha pogut instal·lar WebView2. Proveu de reiniciar l'instal·lador."
LangString webview2DownloadError ${LANG_CATALAN} "Error: no s'ha pogut baixar WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_CATALAN} "El bootstrapper de WebView2 s'ha baixat correctament."
LangString webview2Downloading ${LANG_CATALAN} "S'està baixant el bootstrapper de WebView2..."
LangString webview2InstallError ${LANG_CATALAN} "Error: la instal·lació de WebView2 ha fallat amb el codi $1."
LangString webview2InstallSuccess ${LANG_CATALAN} "WebView2 s'ha instal·lat correctament."
LangString deleteAppData ${LANG_CATALAN} "Elimina les dades de l'aplicació"
