//! Sidecar bundle extraction + SHA-256 integrity helpers.
//!
//! Split out of [`crate::sidecar`] (2026-05-30) to keep that module
//! under the 500-NLOC budget. Contains the lazy first-launch extraction of
//! `sidecar-bundle.tar.gz` to `app_data_dir/sidecar/` and the SHA-256 digest
//! parsing/verification helpers it relies on.
//!
//! The state types, port helpers, path resolvers and restart guard stay in
//! [`crate::sidecar`].

/// Extract `sidecar-bundle.tar.gz` to `app_data_dir/sidecar/` on first launch.
///
/// The tarball contains `venv/` and `app/`. The `nexe-sidecar` launcher is managed
/// separately by Tauri `externalBin` (`Contents/MacOS/nexe-sidecar`).
///
/// A SHA-256-stamped `.extracted` marker prevents re-extraction on every launch.
/// The marker holds the SHA-256 of the bundled `sidecar-bundle.tar.gz` (read from
/// the sibling `sidecar-bundle.sha256` resource generated by
/// `scripts/pre-bundle-sidecar.sh`). Re-extraction occurs automatically whenever
/// the tarball SHA changes — even within the same `CARGO_PKG_VERSION` — so dev
/// re-builds propagate cleanly without manual `rm -rf` of the sidecar dir.
///
/// Fallback: when the SHA resource is absent or empty (CI placeholder, or
/// DMGs built before this change), `CARGO_PKG_VERSION` is used instead, matching
/// the pre-2026-05-22 behaviour. Old markers (version text) remain interpretable.
///
/// Returns the `sidecar_dir` path so the caller can pass it as `NEXE_SIDECAR_DIR`
/// to the launcher process.
/// A `.extract.lock` older than this threshold is considered stale (left
/// behind by a process killed mid-extraction) and is safe to remove.
const STALE_LOCK_SECS: u64 = 300;

/// Returns `true` when `lock_path` exists and its mtime is older than
/// [`STALE_LOCK_SECS`]. Returns `false` on any I/O error or if the file is
/// absent — the caller treats those as "not stale".
fn is_lock_stale(lock_path: &std::path::Path) -> bool {
    std::fs::metadata(lock_path)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.elapsed().ok())
        .map(|d| d.as_secs() > STALE_LOCK_SECS)
        .unwrap_or(false)
}

// Dead in debug builds (called only under #[cfg(not(debug_assertions))]).
#[cfg_attr(debug_assertions, allow(dead_code))]
pub(crate) fn ensure_sidecar_extracted(
    app: &tauri::AppHandle,
) -> Result<std::path::PathBuf, String> {
    use tauri::Manager;

    let data_dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("app_data_dir: {e}"))?;
    let sidecar_dir = data_dir.join("sidecar");
    let marker = sidecar_dir.join(".extracted");

    // Resolve the expected marker value once (SHA preferred, version fallback).
    // Reading it before the `needs_extract` check is what lets the lock-loser
    // branch below detect completion correctly.
    let expected =
        read_sidecar_sha256(app).unwrap_or_else(|| env!("CARGO_PKG_VERSION").to_string());

    let needs_extract = match std::fs::read_to_string(&marker) {
        Ok(v) => v.trim() != expected,
        Err(_) => true,
    };

    if needs_extract {
        let tarball = app
            .path()
            .resolve(
                "sidecar-bundle.tar.gz",
                tauri::path::BaseDirectory::Resource,
            )
            .map_err(|e| format!("resolve sidecar-bundle.tar.gz: {e}"))?;
        tracing::info!(
            src = %tarball.display(),
            dest = %sidecar_dir.display(),
            expected = %expected,
            "extracting sidecar bundle"
        );
        std::fs::create_dir_all(&sidecar_dir).map_err(|e| format!("create sidecar dir: {e}"))?;

        // Prevent two app launches from racing to
        // unpack the same tarball into the same target dir (interleaved writes
        // corrupt the venv). Acquire an exclusive lock-file with O_EXCL; the
        // loser of the race waits for the .extracted marker to appear and then
        // skips the extraction altogether.
        let lock_path = sidecar_dir.join(".extract.lock");
        let lock = match std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&lock_path)
        {
            Ok(f) => f,
            Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
                if is_lock_stale(&lock_path) {
                    tracing::warn!(
                        lock = %lock_path.display(),
                        "stale .extract.lock (>{}s); removing and retrying",
                        STALE_LOCK_SECS
                    );
                    let _ = std::fs::remove_file(&lock_path);
                    match std::fs::OpenOptions::new()
                        .write(true)
                        .create_new(true)
                        .open(&lock_path)
                    {
                        Ok(f) => f,
                        Err(e) => {
                            return Err(format!(
                                "acquire extract lock after stale removal {}: {e}",
                                lock_path.display()
                            ))
                        }
                    }
                } else {
                    tracing::info!(
                        lock = %lock_path.display(),
                        "another process is extracting the sidecar bundle; waiting"
                    );
                    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(120);
                    while std::time::Instant::now() < deadline {
                        if matches!(std::fs::read_to_string(&marker), Ok(v) if v.trim() == expected)
                        {
                            return Ok(sidecar_dir);
                        }
                        std::thread::sleep(std::time::Duration::from_millis(200));
                    }
                    return Err(format!(
                        "timed out waiting for concurrent sidecar extraction (lock {})",
                        lock_path.display()
                    ));
                }
            }
            Err(e) => return Err(format!("acquire extract lock {}: {e}", lock_path.display())),
        };

        // RAII guard removes the lock file when this scope ends (success or panic).
        struct LockGuard {
            path: std::path::PathBuf,
        }
        impl Drop for LockGuard {
            fn drop(&mut self) {
                let _ = std::fs::remove_file(&self.path);
            }
        }
        let _guard = LockGuard {
            path: lock_path.clone(),
        };
        drop(lock); // close handle; the file is removed by the guard on scope exit

        // When a sibling `sidecar-bundle.sha256` resource is
        // present (one hex digest per line, first line wins), verify the SHA-256
        // of the tarball before unpacking. The file is optional for now so
        // existing builds keep working — a future release will start shipping
        // the digest alongside every bundle to make this check mandatory.
        if let Err(e) = verify_tarball_sha256(app, &tarball) {
            return Err(format!("sidecar bundle integrity check failed: {e}"));
        }

        let file =
            std::fs::File::open(&tarball).map_err(|e| format!("open sidecar tarball: {e}"))?;
        let gz = flate2::read::GzDecoder::new(file);
        let mut archive = tar::Archive::new(gz);
        archive.set_overwrite(true);
        archive
            .unpack(&sidecar_dir)
            .map_err(|e| format!("unpack sidecar tarball: {e}"))?;
        // Atomic marker write: tempfile + rename. `rename(2)` is atomic on APFS
        // and HFS+ when source and dest live on the same filesystem, so a
        // force-quit during the write cannot leave a corrupt marker behind.
        let marker_tmp = sidecar_dir.join(".extracted.tmp");
        std::fs::write(&marker_tmp, &expected)
            .map_err(|e| format!("write .extracted.tmp marker: {e}"))?;
        std::fs::rename(&marker_tmp, &marker)
            .map_err(|e| format!("rename .extracted marker into place: {e}"))?;
        tracing::info!("sidecar bundle extracted ok");
    }

    Ok(sidecar_dir)
}

/// Read the bundled `sidecar-bundle.sha256` resource and return the SHA-256
/// digest as a lowercase 64-char hex string. Returns `None` when:
/// - the resource cannot be resolved (no bundle, dev mode, missing path),
/// - the file is missing on disk,
/// - the file is empty (`build.rs` placeholder used by `cargo test` / CI),
/// - the first whitespace-separated token isn't a valid 64-char hex digest.
///
/// Callers use the returned SHA as the `.extracted` marker payload to detect
/// re-builds within the same `CARGO_PKG_VERSION`. When `None` is returned they
/// fall back to `CARGO_PKG_VERSION`, matching the pre-2026-05-22 behaviour.
#[cfg_attr(debug_assertions, allow(dead_code))]
fn read_sidecar_sha256(app: &tauri::AppHandle) -> Option<String> {
    use tauri::Manager;
    let path = app
        .path()
        .resolve(
            "sidecar-bundle.sha256",
            tauri::path::BaseDirectory::Resource,
        )
        .ok()?;
    if !path.is_file() {
        return None;
    }
    let meta = std::fs::metadata(&path).ok()?;
    if meta.len() == 0 {
        // build.rs / CI placeholder — treat as absent so the fallback kicks in
        // instead of failing the launch.
        return None;
    }
    let raw = std::fs::read_to_string(&path).ok()?;
    parse_sha256_digest(&raw)
}

/// Parse the first whitespace-separated token of `raw` as a SHA-256 hex digest.
/// Returns `Some(lowercase_hex)` on success, `None` otherwise. Pulled out as a
/// pure helper so it can be unit-tested without a Tauri `AppHandle`.
#[cfg_attr(debug_assertions, allow(dead_code))]
fn parse_sha256_digest(raw: &str) -> Option<String> {
    let token = raw.lines().next()?.split_whitespace().next()?;
    let lower = token.to_ascii_lowercase();
    if lower.len() == 64 && lower.chars().all(|c| c.is_ascii_hexdigit()) {
        Some(lower)
    } else {
        None
    }
}

/// Verify the SHA-256 of `tarball` against the expected digest
/// shipped as `sidecar-bundle.sha256` in the bundle resources. When the digest
/// file is missing the function returns `Ok(())` so old builds keep working;
/// future release builds will start shipping the digest unconditionally.
#[cfg_attr(debug_assertions, allow(dead_code))]
fn verify_tarball_sha256(app: &tauri::AppHandle, tarball: &std::path::Path) -> Result<(), String> {
    use tauri::Manager;

    let digest_resource = match app.path().resolve(
        "sidecar-bundle.sha256",
        tauri::path::BaseDirectory::Resource,
    ) {
        Ok(p) => p,
        Err(_) => {
            tracing::warn!(
                "sidecar-bundle.sha256 not bundled; skipping integrity check (transitional)"
            );
            return Ok(());
        }
    };
    verify_tarball_against_digest_path(tarball, &digest_resource)
}

/// Apply the transitional fail-open policy to an *already-resolved* digest path.
/// Split out of [`verify_tarball_sha256`] so the two skip branches (missing file
/// / empty file) can be unit-tested without a Tauri `AppHandle`. Behaviour is
/// identical to the previously-inlined version: a missing or empty digest file
/// skips verification and returns `Ok(())`; a present, non-empty digest file is
/// verified against `tarball`.
#[cfg_attr(debug_assertions, allow(dead_code))]
fn verify_tarball_against_digest_path(
    tarball: &std::path::Path,
    digest_resource: &std::path::Path,
) -> Result<(), String> {
    if !digest_resource.is_file() {
        tracing::warn!(
            path = %digest_resource.display(),
            "sidecar-bundle.sha256 missing; skipping integrity check (transitional)"
        );
        return Ok(());
    }
    // Tolerate empty placeholder created by build.rs for `cargo test` / CI
    // (`pnpm tauri build --no-bundle`). Treating it as "no digest available"
    // matches the `read_sidecar_sha256` fallback so both paths agree.
    if std::fs::metadata(digest_resource)
        .map(|m| m.len() == 0)
        .unwrap_or(false)
    {
        tracing::warn!(
            path = %digest_resource.display(),
            "sidecar-bundle.sha256 is empty (CI placeholder); skipping integrity check"
        );
        return Ok(());
    }
    verify_sha256_against_digest_file(tarball, digest_resource)
}

/// Pure helper extracted from [`verify_tarball_sha256`] so it can be exercised
/// from unit tests without a Tauri `AppHandle`. Reads the first whitespace
/// token of `digest_file`, validates it as a 64-char hex digest, and compares
/// it with the SHA-256 of `tarball` (streamed in 64 KiB chunks to keep memory
/// bounded for large bundles).
#[cfg_attr(debug_assertions, allow(dead_code))]
fn verify_sha256_against_digest_file(
    tarball: &std::path::Path,
    digest_file: &std::path::Path,
) -> Result<(), String> {
    use sha2::{Digest, Sha256};
    use std::io::Read;

    let expected_raw = std::fs::read_to_string(digest_file)
        .map_err(|e| format!("read {}: {e}", digest_file.display()))?;
    let expected = expected_raw
        .lines()
        .next()
        .ok_or_else(|| "expected digest file is empty".to_string())?
        .split_whitespace()
        .next()
        .ok_or_else(|| "expected digest line has no token".to_string())?
        .to_ascii_lowercase();
    if expected.len() != 64 || !expected.chars().all(|c| c.is_ascii_hexdigit()) {
        return Err(format!(
            "expected digest is not a 64-char hex string: {expected:?}"
        ));
    }

    let mut hasher = Sha256::new();
    let mut file = std::fs::File::open(tarball).map_err(|e| format!("open tarball: {e}"))?;
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = file
            .read(&mut buf)
            .map_err(|e| format!("read tarball: {e}"))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    let actual = format!("{:x}", hasher.finalize());
    if actual != expected {
        return Err(format!(
            "SHA-256 mismatch: expected {expected}, got {actual}"
        ));
    }
    tracing::info!("sidecar bundle SHA-256 verified");
    Ok(())
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;

    fn mktemp_root(test_name: &str) -> PathBuf {
        let base = std::env::temp_dir().join(format!(
            "nexe-sidecar-extract-test-{}-{}",
            test_name,
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&base);
        fs::create_dir_all(&base).unwrap();
        base
    }

    // ─── verify_sha256_against_digest_file ────────────────────

    /// Known-good SHA-256 for `b"nexe-sidecar-test-payload\n"`.
    /// Verified once with `printf 'nexe-sidecar-test-payload\n' | shasum -a 256`.
    const KNOWN_PAYLOAD: &[u8] = b"nexe-sidecar-test-payload\n";
    const KNOWN_SHA256: &str = "22cfb3d72fd97742766e852191be3d811f4b98cc63643c674e08a654a38a8db1";

    fn write_fixture(dir: &std::path::Path, name: &str, contents: &[u8]) -> PathBuf {
        let p = dir.join(name);
        fs::write(&p, contents).unwrap();
        p
    }

    #[test]
    fn verify_sha256_against_digest_file_passes_on_match() {
        let root = mktemp_root("sha256-match");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest = write_fixture(&root, "bundle.sha256", KNOWN_SHA256.as_bytes());
        super::verify_sha256_against_digest_file(&tarball, &digest)
            .expect("matching digest must pass");
    }

    #[test]
    fn verify_sha256_against_digest_file_passes_with_trailing_filename() {
        // `shasum -a 256` outputs `<hex>  <filename>`; we want the first token to win.
        let root = mktemp_root("sha256-with-filename");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest_line = format!("{KNOWN_SHA256}  bundle.tar.gz\n");
        let digest = write_fixture(&root, "bundle.sha256", digest_line.as_bytes());
        super::verify_sha256_against_digest_file(&tarball, &digest)
            .expect("digest line with filename should still pass");
    }

    #[test]
    fn verify_sha256_against_digest_file_rejects_mismatch() {
        let root = mktemp_root("sha256-mismatch");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let bogus = "0".repeat(64);
        let digest = write_fixture(&root, "bundle.sha256", bogus.as_bytes());
        let err = super::verify_sha256_against_digest_file(&tarball, &digest)
            .expect_err("mismatched digest must fail");
        assert!(err.contains("SHA-256 mismatch"), "got {err:?}");
    }

    #[test]
    fn verify_sha256_against_digest_file_rejects_malformed_digest() {
        let root = mktemp_root("sha256-malformed");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest = write_fixture(&root, "bundle.sha256", b"not-a-hex-digest\n");
        let err = super::verify_sha256_against_digest_file(&tarball, &digest)
            .expect_err("malformed digest must fail");
        assert!(
            err.contains("64-char hex"),
            "expected hex validation error, got {err:?}"
        );
    }

    #[test]
    fn verify_sha256_against_digest_file_rejects_empty_digest_file() {
        let root = mktemp_root("sha256-empty");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest = write_fixture(&root, "bundle.sha256", b"");
        let err = super::verify_sha256_against_digest_file(&tarball, &digest)
            .expect_err("empty digest must fail");
        assert!(
            err.contains("empty") || err.contains("no token"),
            "expected empty-file error, got {err:?}"
        );
    }

    // ─── 2026-05-22 — .extracted marker SHA-256 + helpers ────────────────────

    /// `parse_sha256_digest` accepts a bare 64-char hex digest with trailing newline.
    #[test]
    fn parse_sha256_digest_accepts_bare_hex() {
        let parsed = super::parse_sha256_digest(&format!("{KNOWN_SHA256}\n"))
            .expect("bare hex digest should parse");
        assert_eq!(parsed, KNOWN_SHA256);
    }

    /// `parse_sha256_digest` accepts `<hex>  <filename>` (default `shasum -a 256` output).
    #[test]
    fn parse_sha256_digest_accepts_hex_with_filename() {
        let line = format!("{KNOWN_SHA256}  sidecar-bundle.tar.gz\n");
        let parsed =
            super::parse_sha256_digest(&line).expect("hex+filename line should parse to bare hex");
        assert_eq!(parsed, KNOWN_SHA256);
    }

    /// `parse_sha256_digest` normalises uppercase hex to lowercase.
    #[test]
    fn parse_sha256_digest_lowercases_uppercase_hex() {
        let upper = KNOWN_SHA256.to_ascii_uppercase();
        let parsed = super::parse_sha256_digest(&upper).expect("uppercase hex should parse");
        assert_eq!(parsed, KNOWN_SHA256);
    }

    /// `parse_sha256_digest` returns `None` for empty input (CI placeholder).
    #[test]
    fn parse_sha256_digest_rejects_empty_input() {
        assert!(super::parse_sha256_digest("").is_none());
    }

    /// `parse_sha256_digest` returns `None` for non-hex / wrong-length tokens.
    #[test]
    fn parse_sha256_digest_rejects_non_hex_or_wrong_length() {
        assert!(super::parse_sha256_digest("not-a-hex-digest\n").is_none());
        assert!(super::parse_sha256_digest("abc123\n").is_none());
        // 64 chars but contains a non-hex letter
        let bad = format!("{}z", &KNOWN_SHA256[..63]);
        assert!(super::parse_sha256_digest(&bad).is_none());
    }

    /// Lock-loser branch contract: the polling loop in `ensure_sidecar_extracted`
    /// returns successfully when the marker matches `expected`. This pins the
    /// invariant the 2026-05-22 refactor introduced (previously it compared
    /// against `current_version` literally, which broke with SHA markers).
    #[test]
    fn marker_matches_expected_when_content_equal() {
        let root = mktemp_root("marker-match");
        let marker = root.join(".extracted");
        fs::write(&marker, KNOWN_SHA256).unwrap();
        let read = fs::read_to_string(&marker).unwrap();
        assert_eq!(read.trim(), KNOWN_SHA256);
    }
    // The actual lock-loser polling loop is exercised end-to-end by integration
    // tests using a real AppHandle; this unit test pins the comparison contract
    // (`marker.trim() == expected`) that the loop relies on.

    // ─── K-001 — stale lock detection ─────────────────────────────────────────

    #[test]
    fn stale_lock_detected_above_threshold() {
        let root = mktemp_root("stale-lock-detect");
        let lock_path = root.join(".extract.lock");
        let f = std::fs::File::create(&lock_path).unwrap();
        let old_time = std::time::SystemTime::now()
            .checked_sub(std::time::Duration::from_secs(600))
            .unwrap();
        f.set_modified(old_time).unwrap();
        assert!(super::is_lock_stale(&lock_path));
    }

    #[test]
    fn fresh_lock_not_detected_as_stale() {
        let root = mktemp_root("fresh-lock");
        let lock_path = root.join(".extract.lock");
        std::fs::File::create(&lock_path).unwrap();
        // mtime = now (just created) — well within STALE_LOCK_SECS
        assert!(!super::is_lock_stale(&lock_path));
    }

    #[test]
    fn missing_lock_not_stale() {
        let root = mktemp_root("missing-lock");
        let lock_path = root.join(".extract.lock");
        // File does not exist — unwrap_or(false) in is_lock_stale
        assert!(!super::is_lock_stale(&lock_path));
    }

    // ─── BONUS-003 — verify_tarball_against_digest_path fail-open branches ─────
    // Pins the transitional policy so a packaging bug (dropped/empty .sha256) or
    // a refactor cannot silently flip skip↔verify without a failing test.

    /// Missing digest file → fail-open skip (transitional). Note this is the
    /// OPPOSITE of `verify_sha256_against_digest_file`, which errors on a missing
    /// digest — the skip lives in this seam, and this test locks it in.
    #[test]
    fn digest_missing_skips_verification() {
        let root = mktemp_root("digest-missing");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest = root.join("does-not-exist.sha256");
        super::verify_tarball_against_digest_path(&tarball, &digest)
            .expect("missing digest must fail-open (transitional skip)");
    }

    /// Empty digest file (CI/build.rs placeholder) → fail-open skip. Again the
    /// opposite of the terminal helper, which errors on an empty file.
    #[test]
    fn digest_empty_skips_verification() {
        let root = mktemp_root("digest-empty-skip");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest = write_fixture(&root, "bundle.sha256", b"");
        super::verify_tarball_against_digest_path(&tarball, &digest)
            .expect("empty digest must fail-open (transitional skip)");
    }

    /// Present + matching digest → verifies and passes.
    #[test]
    fn digest_present_matching_passes() {
        let root = mktemp_root("digest-present-match");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let digest = write_fixture(&root, "bundle.sha256", KNOWN_SHA256.as_bytes());
        super::verify_tarball_against_digest_path(&tarball, &digest)
            .expect("present matching digest must pass");
    }

    /// Present + mismatched digest → hard failure (tamper rejection end-to-end
    /// through the same seam `verify_tarball_sha256` uses).
    #[test]
    fn digest_present_mismatch_fails() {
        let root = mktemp_root("digest-present-mismatch");
        let tarball = write_fixture(&root, "bundle.tar.gz", KNOWN_PAYLOAD);
        let bogus = "1".repeat(64);
        let digest = write_fixture(&root, "bundle.sha256", bogus.as_bytes());
        let err = super::verify_tarball_against_digest_path(&tarball, &digest)
            .expect_err("present mismatched digest must fail");
        assert!(err.contains("SHA-256 mismatch"), "got {err:?}");
    }

    // ─── BONUS-002 — tar extraction traversal / symlink-escape regression pins ─
    // The `tar` crate sanitises `..` and symlink-escapes on unpack today; these
    // tests pin that behaviour so a `tar` bump or a set_preserve_permissions/
    // symlink-follow change can't silently weaken it undetected.

    fn gzip(bytes: &[u8]) -> Vec<u8> {
        use std::io::Write;
        let mut enc =
            flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
        enc.write_all(bytes).unwrap();
        enc.finish().unwrap()
    }

    /// Recompute the ustar header checksum for a 512-byte header block after its
    /// name field has been tampered with. The `tar` builder refuses to *write* a
    /// `..` path, so we forge one by patching the name bytes and re-signing.
    fn fix_ustar_cksum(block: &mut [u8]) {
        assert_eq!(block.len(), 512);
        // Checksum is computed with the 8-byte chksum field (148..156) as spaces.
        for b in block[148..156].iter_mut() {
            *b = b' ';
        }
        let sum: u32 = block.iter().map(|&b| b as u32).sum();
        let digits = format!("{sum:06o}");
        block[148..154].copy_from_slice(digits.as_bytes());
        block[154] = 0;
        block[155] = b' ';
    }

    /// Run the exact production extraction path: GzDecoder + `Archive::unpack`
    /// with `set_overwrite(true)`, into `dest`.
    fn unpack_gz_into(gz: &[u8], dest: &std::path::Path) -> Result<(), String> {
        let gzr = flate2::read::GzDecoder::new(std::io::Cursor::new(gz.to_vec()));
        let mut archive = tar::Archive::new(gzr);
        archive.set_overwrite(true);
        archive.unpack(dest).map_err(|e| e.to_string())
    }

    /// A tarball whose first entry name is `../escape` must never write outside
    /// the destination dir.
    #[test]
    fn tar_unpack_rejects_parent_dir_traversal() {
        let root = mktemp_root("tar-traversal");
        let dest = root.join("sidecar");
        fs::create_dir_all(&dest).unwrap();

        // Build a valid tar with placeholder name `zz/escape`, then forge the
        // name into `../escape` and re-sign the header (the builder rejects `..`).
        let mut builder = tar::Builder::new(Vec::new());
        let payload = b"pwned";
        let mut h = tar::Header::new_gnu();
        h.set_size(payload.len() as u64);
        h.set_mode(0o644);
        h.set_entry_type(tar::EntryType::Regular);
        builder
            .append_data(&mut h, "zz/escape", &payload[..])
            .unwrap();
        // A safe sibling so the archive still contains something extractable.
        let mut hs = tar::Header::new_gnu();
        hs.set_size(payload.len() as u64);
        hs.set_mode(0o644);
        hs.set_entry_type(tar::EntryType::Regular);
        builder
            .append_data(&mut hs, "safe.txt", &payload[..])
            .unwrap();
        let mut tar_bytes = builder.into_inner().unwrap();

        // Forge `zz/escape` → `../escape` in the first header's name field (0..).
        assert_eq!(&tar_bytes[0..9], &b"zz/escape"[..]);
        tar_bytes[0] = b'.';
        tar_bytes[1] = b'.';
        fix_ustar_cksum(&mut tar_bytes[0..512]);

        let gz = gzip(&tar_bytes);
        // `tar` sanitises `..` by skipping the entry (unpack may still be Ok).
        let _ = unpack_gz_into(&gz, &dest);

        // The forged entry must NOT have escaped to `<root>/escape`.
        let escaped = root.join("escape");
        assert!(
            !escaped.exists(),
            "path-traversal entry escaped extraction dir: {}",
            escaped.display()
        );
        assert!(!dest.join("escape").exists());
    }

    /// A symlink pointing outside the destination followed by a file written
    /// *through* it must never create anything outside the destination dir.
    #[test]
    fn tar_unpack_rejects_symlink_escape() {
        let root = mktemp_root("tar-symlink");
        let dest = root.join("sidecar");
        fs::create_dir_all(&dest).unwrap();

        let mut builder = tar::Builder::new(Vec::new());
        // symlink `link` -> `../escape_target` (resolves outside `dest`).
        let mut lh = tar::Header::new_gnu();
        lh.set_size(0);
        lh.set_mode(0o777);
        lh.set_entry_type(tar::EntryType::Symlink);
        builder
            .append_link(&mut lh, "link", "../escape_target")
            .unwrap();
        // file `link/evil.txt` that would land in `../escape_target/` if the
        // symlink were followed during extraction.
        let payload = b"evil";
        let mut fh = tar::Header::new_gnu();
        fh.set_size(payload.len() as u64);
        fh.set_mode(0o644);
        fh.set_entry_type(tar::EntryType::Regular);
        builder
            .append_data(&mut fh, "link/evil.txt", &payload[..])
            .unwrap();
        let tar_bytes = builder.into_inner().unwrap();

        let gz = gzip(&tar_bytes);
        let _ = unpack_gz_into(&gz, &dest);

        // Nothing may have been written outside `dest`.
        assert!(
            !root.join("escape_target").exists(),
            "symlink escape created files outside extraction dir"
        );
    }
}
